### ISSUE TITLE
Define Interfaces

### ISSUE THREAD

**Issue by mtopolski** [TectonicSonic/TectonicSonic#2]

**Comment by horologix** [comment]
What do you mean define interfaces.

**Comment by mtopolski** [comment]
The plan is deliver this payload to every user 'subcribed' for each turn

{
  min stake- num
  last move- 'bet'
  turn- uid
  tablecards
  users: [{
    hand: cards
    money: num,
    active: bool,
    stake: num,
    seat: num
}]
}
